### ISSUE TITLE
Composer install with TYPO3 11.5 isn't working, it req TYPO3 10.

### ISSUE THREAD

**Issue by migaduo** [itplusx/headless_gridelements#15]
Hey guys,

maybe there is a small issue with the compatibility of TYPO3 in your composer.json. It requires TYPO3  typo3/cms-core ^10.0 and not 11.0. 

Just a small reminder.

Thanks!

**Comment by schloram** [comment]
Hi @migaduo,
what headless_gridelements version are you referring to?

**Comment by migaduo** [comment]
Hey @schloram,

i used the composer cmd `composer req itplusx/headless-gridelements` and it's v2.1.0.

**Comment by migaduo** [comment]
@schloram sorry, it's my fault. I had an old composer.json in my project with cms-core 10.0 and i forgot to update it. 

I think this issue is closed. :) Thanks for your fast respond.

**Comment by schloram** [comment]
Yeah, that's intentional.

Because `gridelementsteam/gridelements` is still not publicly released for TYPO3 v11, it makes no sense to release `headless_gridelements` for TYPO3 v11.

If you want to tinker a little bit with this extension and  TYPO3 v11 you need to checkout `dev-main`:

`composer req itplusx/headless-gridelements:v3.0` (`"minimum-stability": "dev"` must be set)

But currently I have no idea if the public gridelements even work with v11. Last time I checked I suddenly got an Exception making my TYPO3 instance inoperable.

**Comment by migaduo** [comment]
Yeah, i start a prototype with EXT:headless and TYPO3 v11. But i want to add EXT:gridelements to it because i really need it.
And the next problem will be npm nuxt-typo3 with this whole setup.

Thanks mate!
