### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kitzberger** [itplusx/headless_gridelements#16]
The latest release `2.x` is incompatible to TYPO3 11. `dev-main` is though, for a while now and only lacking a semantic release number, right?

**Comment by schloram** [comment]
@kitzberger That is (kinda) correct. :)

But since [gridelements](https://extensions.typo3.org/extension/gridelements) itself isn't compatible with TYPO3 11 and this extension is fully based on it I don't feel confident to release our extension for TYPO3 11. On our `dev-main` we require `gridelements:dev-master`. If we do this in a proper release this would break our release anytime gridelements changes things we are using on master.

At some point the gridelements extension was even completely broken on `dev-master`. I don't want to risk this in our release.

Currently we are working on a `EXT:headless_container` which utilizes the [EXT:container](https://github.com/b13/container) from b13 because we are a little annoyed by gridelements and their release strategy.

**Comment by schloram** [comment]
@kitzberger You could check out [EXT:headless_container](https://github.com/itplusx/headless-container) and test it. We would be happy to receive your honest feedback. :)

We're currently testing it and plan to release this soon.
Also we're in discussion about the official TER Key because this is already taken by another agency but not used yet.
