### ISSUE TITLE
LLL references within column names are not being resolved

### ISSUE THREAD

**Issue by kitzberger** [itplusx/headless_gridelements#8]
In the resulting JSON the LLL references within column names are not being resolved at the moment.

**Comment by schloram** [comment]
Thanks for your contribution again. You are right the column name should be translatable for the frontend. Thanks for pointing that out and fixing it.

We were always using non-translated column names and were never really using them in the frontend, that's why this never came to our mind. 👍

I will bundle this in a release (v2.0.2) this week. In the meanwhile you could install `2.0.x-dev`.
